# Generated by Django 2.0.5 on 2018-11-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_banners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banners',
            old_name='postion',
            new_name='position',
        ),
        migrations.AlterField(
            model_name='banners',
            name='bannersimg',
            field=models.URLField(null=True),
        ),
    ]
